### ISSUE TITLE
Update of MA Binaries on system overwrites log files

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/googleapps-managementagent#14]
It looks like if we do a new update of Google MA Binaries on sync server, it wipes existing log file and creates a new one instead of append.

**Comment by ryannewington** [comment]
No, it definitely doesnt

**Comment by khandelwalpiyush** [comment]
It is indeed not the issue .. Had been noticing this behavior for quite some time.. but have found an internal bug in our deployment and not related to the MA..
