### ISSUE TITLE
Build number not updated in v1.1.6450

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/googleapps-managementagent#16]
Unable to upgrade from [v1.1.6222](https://github.com/lithnet/googleapps-managementagent/releases/tag/v1.1.6222) to [v1.1.6450](https://github.com/lithnet/googleapps-managementagent/releases/tag/v1.1.6450) as the installer thinks newer version is already installed

**Comment by ryannewington** [comment]
Thanks @khandelwalpiyush. Fixed in 1.1.6451
