### ISSUE TITLE
How to add more than one type per box in Schema tab

### ISSUE THREAD

**Issue by IAmStevenJohnson** [lithnet/googleapps-managementagent#22]
If I'm reading your instructions correctly, I should be able to add more than one type per box on the Schema tab of the MA. The instructions say to add one per line. How to you get another line? If I press the ENTER key after typing one entry in a box, it selects the OK box and goes to another tab. Am I missing something?

**Comment by ryannewington** [comment]
@IAmStevenJohnson Those FIM text boxes require you to press Ctrl+Enter for a new line. I'll make a note of this in the documentation.
