### ISSUE TITLE
Google's service account names have changed?

### ISSUE THREAD

**Issue by IAmStevenJohnson** [lithnet/googleapps-managementagent#29]
I'm wondering if you know what type of service account should now be created as it appears they've changed it from your documentation. Here is what I see now:

![image](https://user-images.githubusercontent.com/37386921/40555799-7c813198-6007-11e8-82c9-15fc05ca16a3.png)

**Comment by ryannewington** [comment]
Hi @IAmStevenJohnson 
Thanks for pointing this out. The correct role is "Service account user" and I've updated the wiki to reflect this.

Ryan
