### ISSUE TITLE
The RateLimit configuration item does not seem to be used 

### ISSUE THREAD

**Issue by leoerlandsson** [lithnet/googleapps-managementagent#35]
The RateLimit configuration item ("rate-limit") does not seem to be used in v2.0.6954 when creating the buckets.
(E.g. DirectoryApiElement.RateLimit)

This leads to default rate limits being used, and not configurable.

Could you please check?

**Comment by ryannewington** [comment]
Do you know what the rate limit for classrooms actually is by default
https://developers.google.com/classroom/limits

The default in the Lithnet.GoogleApp code was 48/10 seconds, but the default in the configSection for ClassroomApiElement.cs was 500.

I've set it to 50/second as per the above document, but not sure if that is correct

**Comment by leoerlandsson** [comment]
It should be 5/second (or 50/10 seconds).

I tried the higher number (5000 per 100 seconds or 50/sec) and got lots of 429 Backoff responses.

**Comment by ryannewington** [comment]
Fixed in 1.0.6996
