### ISSUE TITLE
Deprecated API question

### ISSUE THREAD

**Issue by LukaszKrukowski** [lithnet/googleapps-managementagent#38]
Hi @ryannewington 

Trusting you're fine.

I would like to double check with you that it is ok to remove following deprecated API - https://apps-apis.google.com/a/feeds/emailsettings/2.0/ (as per this article: https://gsuiteupdates.googleblog.com/2018/10/email-settings-api-shutdown.html) from Client Access API's. It appears that GoogleApps MA works just fine without it but wanted to check with you before implementing that change in the production environment. Can you think of any functionalities that may not be working properly without this API please?

Kind regards,
Lukasz

**Comment by ryannewington** [comment]
Hi @LukaszKrukowski ,

If you are using the current pre-release version then yes, you no longer need the email settings api. This was only used for delegate support on advanced users, and sendas support. The APIs for managing delegates has been moved over to the new gmail API. 

While this code is production ready, the calendar support in this branch forms part of the upcoming version 2.0 release of this connector, and that is still in testing.

Ryan

**Comment by ryannewington** [comment]
There will be some release notes to help people change their oauth scopes, but otherwise it's just an install over the top. No FIM sync restart required, just an MA refresh.

**Comment by LukaszKrukowski** [comment]
Fantastic, I will keep an eye open for the new release then. Thank you very much for your help, as always!

Kind regards,
Lukasz

**Comment by ryannewington** [comment]
Just to close the loop in this, the new MA version is available here https://github.com/lithnet/googleapps-managementagent/releases/tag/v2.0.6996
