### ISSUE TITLE
Addresses and Relations attribute types not available for Contacts

### ISSUE THREAD

**Issue by IAmStevenJohnson** [lithnet/googleapps-managementagent#42]
Using v2 of the MA and when adding Addresses and Relations fixed types to the Schema 1 tab they aren't available to use in attribute flows for Contacts. They show up in the Select Attributes tab and can be used for User attribute flows, just not Contacts. Any ideas why?

Added to the Schema 1 tab:
![image](https://user-images.githubusercontent.com/37386921/57319398-b33eaa80-70b9-11e9-90cc-975cbf4eebda.png)

And selected on the Select Attributes tab: 
![image](https://user-images.githubusercontent.com/37386921/57319004-ce5cea80-70b8-11e9-9784-eb5846c161f2.png)

![image](https://user-images.githubusercontent.com/37386921/57319022-dcab0680-70b8-11e9-9ec9-d62c502e1515.png)

But they don't show up in the Attribute flows for contacts:
![image](https://user-images.githubusercontent.com/37386921/57319048-efbdd680-70b8-11e9-86a8-2989a51defee.png)
![image](https://user-images.githubusercontent.com/37386921/57319505-f13bce80-70b9-11e9-8084-8edef47c1050.png)

**Comment by leoerlandsson** [comment]
Hi Steven,

I can reproduce this, but the Relations fixed types and the Addresses fixed types are for the _user_ object type. 

So if you select the user object type in attribute flows, you'll find the attributes you're looking for.

Have you previously been able to use these fixes type  for the contact object type?

Br,
Leo

**Comment by IAmStevenJohnson** [comment]
We can set those attributes on contact objects when using GAM. So is there a reason we can't with the MA?

Here's a current contact (with data changed) that we have created with GAM:

> Domain                     : test.domain.com
ContactID                  : 16b665db0aa7e2a2
Name                       : John Smith
Addresses.0.count          : 1
Addresses.1.country        : US
Addresses.1.formatted      : 12345 State Street, Atlanta, GA 12345 US
Addresses.1.locality       : Atlanta
Addresses.1.neighborhood   :
Addresses.1.postalcode     : 12345
Addresses.1.rank           : notprimary
Addresses.1.region         : GA
Addresses.1.streetaddress  : 12345 State Street
Addresses.1.type           : work
Emails.0.count             : 1
Emails.1.address           : john.smith@noemail.com
Emails.1.rank              : primary
Emails.1.type              : work
Family Name                : Smith
Given Name                 : John
Organizations.0.count      : 1
Organizations.1.department : Finance - Business Analysis
Organizations.1.location   :
Organizations.1.name       : ACME Corp
Organizations.1.rank       : notprimary
Organizations.1.title      : Analyst-Fin Ops-Billing
Organizations.1.type       : work
Phones.0.count             : 2
Phones.1.rank              : primary
Phones.1.type              : work
Phones.1.value             : 404-555-1212
Phones.2.rank              : notprimary
Phones.2.type              : mobile
Phones.2.value             : 770-555-1212
Relations.0.count          : 1
Relations.1.type           : manager
Relations.1.value          : Jane.Doe@noemail.com
Updated                    : 2019-04-29T15:28:50.233Z

**Comment by leoerlandsson** [comment]
Ryan emailed me and he's 99% sure that this was never implemented. The reason why (need, tech issue or other) is not clear though (it was a long time ago).
 
So the requested functionality was not supported in V1 of the Connector either.

**Comment by IAmStevenJohnson** [comment]
Leo,

Thanks for checking into this. Do you know if there's any chance of this being added?

**Comment by leoerlandsson** [comment]
Hi Steven,

Hard to say, as I don't know if it was a tech issue or just if the need just wasn't there when Ryan implemented it. Pull Requests are always welcome! :)
