### ISSUE TITLE
Shouldn't release v1.0.7139 be v2.0.7139 ?

### ISSUE THREAD

**Issue by NeedsCoffee** [lithnet/googleapps-managementagent#44]
I just noticed a pre-release has appeared - but it's version 1.0.7139 - aren't we on v2 now?
https://github.com/lithnet/googleapps-managementagent/releases/tag/v1.0.7139

**Comment by ryannewington** [comment]
Wow. Clearly I'm the one that needs coffee. Thanks for picking this up. I've updated the release.
