### ISSUE TITLE
Add staff users to classroom_teachers group

### ISSUE THREAD

**Issue by TheSnootch** [lithnet/googleapps-managementagent#48]
I can't seem to wrap my head around how to do this.  I have users importing/exporting correctly.  Now I want to make sure all my staff are automatically added to the classroom_teachers group.  I've imported the group from Google to the MV but can't figure out how to add the users to the group.  All my staff have an attribute in the metaverse (employeeType=Staff).

Do I need to add code in the extension dll while processing the group object or while processing the staff user object?

I'm pretty sure the code needed is something like:
csentry("members").values.add("user@myusers.com") 

I just don't know where to put it.

**Comment by ryannewington** [comment]
Hi,

You can't typically manipulate objects like that in the metaverse. The MV needs to represent the state of objects in other systems. 

You should flow the group and users into the MIM service. From there, you can create a criteria- based group that adds all your staff into, and flow the membership back out to google.

**Comment by TheSnootch** [comment]
That's unfortunate.  I've never used the MIM MA to do anything.  Any chance you could point me to a step by step document on how to do this?

**Comment by ryannewington** [comment]
I always go back to Carol's guides when it comes to configuring the FIM service. She has lots of helpful guides that should get you through. http://www.wapshere.com/missmiis/fim-walkthroughs-create-the-fim-ma
