### ISSUE TITLE
Fix solely for export hanging

### ISSUE THREAD

**Issue by GitBoruta** [lithnet/googleapps-managementagent#49]
Hi Ryan,

I know that there is a pre-release version of the MA that resolves the export hanging error. However, I don't feel comfortable with installing the pre-release. Could you provide me with a patch for just that issue? Or perhaps the next release is coming soon?

**Comment by ryannewington** [comment]
Hi @GitBoruta,

I can't separate the new chromebook code from the bug fix for the hanging issue. The 'pre-release' part is only the newly added chromebook support. If you dont use that, it's production ready.

This version has been running in production in my own environemnt for 3 months without issue. (180,000 users, 50,000 groups).

I've developed the chromebook support as a request from a user, but they haven't had a chance to test in their environment yet. If they have no issues, then the current release will just be promoted to the current production release.

**Comment by GitBoruta** [comment]
Thanks a lot for such a quick response!

Have a nice day!
