### ISSUE TITLE
domain shared contact object

### ISSUE THREAD

**Issue by briuccio** [lithnet/googleapps-managementagent#51]
Hello,
could you help me to understand why domain shared contacts are not provisioned on google as expected?

I'm only able to create it as below:

<?xml version='1.0' encoding='UTF-8'?>
<entry xmlns='http://www.w3.org/2005/Atom' xmlns:batch='http://schemas.google.com/gdata/batch' xmlns:gd='http://schemas.google.com/g/2005' xmlns:gContact='http://schemas.google.com/contact/2008'>
    <id>http://www.google.com/m8/feeds/contacts/test.fcagroup.com/base/5d4adfc70b7f3c80</id>
    <updated>2020-02-05T09:01:33.666Z</updated>
    <category scheme='http://schemas.google.com/g/2005#kind' term='http://schemas.google.com/contact/2008#contact'/>
    <title type='text'>antani</title>
    <link rel='http://schemas.google.com/contacts/2008/rel#edit-photo' type='image/*' href='https://www.google.com/m8/feeds/photos/media/test.fcagroup.com/5d4adfc70b7f3c80/1B2M2Y8AsgTpgAmY7PhCfg'/>
    <link rel='self' type='application/atom+xml' href='https://www.google.com/m8/feeds/contacts/test.fcagroup.com/full/5d4adfc70b7f3c80'/>
    <link rel='edit' type='application/atom+xml' href='https://www.google.com/m8/feeds/contacts/test.fcagroup.com/full/5d4adfc70b7f3c80/1580893293666000'/>
    <gd:extendedProperty name='lithnet-google-ma-dn' value='groupsharedcontact@test.fcagroup.com'/>
</entry>

As you can see I can't get email address element.
Even if I try to mapping attributes, I can only see "gd:extendedProperty" and "title".
Could you suggest me what is the correct mapping on GoogleMA?

Thanks

**Comment by ryannewington** [comment]
I need a little more information on the problem in order to help. 

1. Are you getting an error message when trying to export a new contact? Or is data just not flowing as expected?
2. Are you able to clear the ma.log file, export a single contact object, and provide the log entries relevant for the export?
3. What do your provisioning and initial attribute flows look like?
4. What do your flow rules look like in the MA itself?

**Comment by briuccio** [comment]
Hi,
1. No, I don't get any error.
2. 
[ma-operations.log](https://github.com/lithnet/googleapps-managementagent/files/4158816/ma-operations.log)
3. 
![import](https://user-images.githubusercontent.com/42810833/73832705-f674a800-4808-11ea-8c72-049fe0e9e0ed.PNG)
4. 
![export](https://user-images.githubusercontent.com/42810833/73832720-fecce300-4808-11ea-8877-f4f460d66e96.PNG)

Thanks.

**Comment by ryannewington** [comment]
Thanks for that information. What comes back into the connector space when you do a *full* import? Is there data missing? Any exported-change-not-reimported errors?

**Comment by briuccio** [comment]
Yes, I have it.
![cs](https://user-images.githubusercontent.com/42810833/73833781-d219cb00-480a-11ea-820c-5bd2716b9248.PNG)

**Comment by ryannewington** [comment]
So the display name attribute doesn't come back in? Is that the problem you are seeing? Do we have this problem with any other attributes?

**Comment by briuccio** [comment]
That's the final connector space. 
![connectorspace](https://user-images.githubusercontent.com/42810833/73835156-3dfd3300-480d-11ea-8a4e-06a724e022c8.PNG)

The attribute that doesn't come back is the email_address.. that is not applied also on google.

Below a GET of the shared contact created by GoogleMA
As you can see, the email address attribute is not defined
That's make not possible to use contact when you compose an email from Google.
It find the "name" but without any address the contact is useless.

   <id>http://www.google.com/m8/feeds/contacts/test.fcagroup.com/base/507d95000912bc51</id>
        <updated>2020-02-05T10:14:08.677Z</updated>
        <category scheme='http://schemas.google.com/g/2005#kind' term='http://schemas.google.com/contact/2008#contact'/>
        <title type='text'>antani</title>
        <link rel='http://schemas.google.com/contacts/2008/rel#edit-photo' type='image/*' href='https://www.google.com/m8/feeds/photos/media/test.fcagroup.com/507d95000912bc51/1B2M2Y8AsgTpgAmY7PhCfg'/>
        <link rel='self' type='application/atom+xml' href='https://www.google.com/m8/feeds/contacts/test.fcagroup.com/full/507d95000912bc51'/>
        <link rel='edit' type='application/atom+xml' href='https://www.google.com/m8/feeds/contacts/test.fcagroup.com/full/507d95000912bc51/1580897648677000'/>
        <gd:extendedProperty name='lithnet-google-ma-dn' value='groupsharedcontact@test.fcagroup.com'/>

**Comment by ryannewington** [comment]
@briuccio 

I think you need to specify "work" in the fixed emails type in the 'schema 1' screen

![image](https://user-images.githubusercontent.com/17229877/73885253-8bd07480-48bb-11ea-9094-a1685641e9b5.png)

You'll then see an 'email_work' attribute appear on the contact object. Flow you email address to that.

**Comment by briuccio** [comment]
@ryannewington Correct! I just came here to tell you that I solve in this way.

Thank you!
