### ISSUE TITLE
Delta Import run profile

### ISSUE THREAD

**Issue by briuccio** [lithnet/googleapps-managementagent#52]
Hello,
as per subject, seems that the run profile "Delta Import" doesn't work.
It starts, it lasts 1 second and no change are imported (even if change are made on Google side).
Are  you aware about this issue? I got this behavior in two different environment, test and prod.

Thanks.

**Comment by ryannewington** [comment]
Google doesn't support delta imports in the way we need them. A delta import for this MA is only a confirming import of what was exported last time. When we export, google returns the confirmed changes to the object. We store that in an xml file and that's what we read on delta import. 

The only way to pull in changes made in google, is to do a full import.

Sorry, but this is the best I could do with the somewhat limited APIs that Google provide.
