### ISSUE TITLE
intitial password?

### ISSUE THREAD

**Issue by herromega** [lithnet/googleapps-managementagent#57]
cant find a way to flow a intial password when creating an account in gapps. should we handle this differently than AD for example?

**Comment by leoerlandsson** [comment]
Hi Tobias,

There should be support for both setting and changing password for users in the LithNet Google MA.
It implements the IMAExtensible2Password interface.

If I'm remembering correctly the attribute should be named "password". Please check and get back if you can't find it.

Br,
Leo

**Comment by leoerlandsson** [comment]
Any update here @herromega  ?

**Comment by herromega** [comment]
after reinstallation i got it to work again.
