### ISSUE TITLE
Log file written to incorrect location on export when http debug is enabled

### ISSUE THREAD

**Issue by khandelwalpiyush** [lithnet/googleapps-managementagent#6]
After latest build [v1.1.6089](https://github.com/lithnet/googleapps-managementagent/releases/tag/v1.1.6089) on an export nothing is written to the log file. On import logs are being written.

**Comment by khandelwalpiyush** [comment]
This is working again.. was not working due to debug logging was enabled. 
Export logging should work even if debug is enabled I had assumed.
If this is not considered a bug then plz close the ticket.

**Comment by ryannewington** [comment]
@khandelwalpiyush what are you referring to when you say 'debug logging'?

**Comment by ryannewington** [comment]
Fixed in [v1.1.6090](https://github.com/lithnet/googleapps-managementagent/releases/tag/v1.1.6090)
