### ISSUE TITLE
Cannot set access type on group

### ISSUE THREAD

**Issue by marcusmaker** [lithnet/googleapps-managementagent#61]
I have a customer that need to change the access settings for groups.
They want the entire org to be able to show members in all groups:
![image](https://user-images.githubusercontent.com/6167423/106295038-3ae62880-6250-11eb-8502-ee14326af043.png)

**Comment by ryannewington** [comment]
Hi Marcus

Theres an attribute called whoCanViewMembership that you need to set to ALL_IN_DOMAIN_CAN_VIEW

![image](https://user-images.githubusercontent.com/17229877/106321957-36aa2180-62c9-11eb-934d-9e0de667c076.jpeg)

![image](https://user-images.githubusercontent.com/17229877/106321968-3a3da880-62c9-11eb-9d66-f114b0a457e2.jpeg)

Ref: https://developers.google.com/admin-sdk/groups-settings/v1/reference/groups

**Comment by marcusmaker** [comment]
Wow, great!

Thank you very much for the info 😊

All the best
/m

Från: Ryan Newington <notifications@github.com>
Skickat: den 29 januari 2021 21:05
Till: lithnet/googleapps-managementagent <googleapps-managementagent@noreply.github.com>
Kopia: Marcus Olsson <marcus@marcusmaker.se>; Author <author@noreply.github.com>
Ämne: Re: [lithnet/googleapps-managementagent] Cannot set access type on group (#61)


Hi Marcus

Theres an attribute called whoCanViewMembership that you need to set to ALL_IN_DOMAIN_CAN_VIEW

[image]<https://user-images.githubusercontent.com/17229877/106321957-36aa2180-62c9-11eb-934d-9e0de667c076.jpeg>

[image]<https://user-images.githubusercontent.com/17229877/106321968-3a3da880-62c9-11eb-9d66-f114b0a457e2.jpeg>

Ref: https://developers.google.com/admin-sdk/groups-settings/v1/reference/groups

**Comment by ryannewington** [comment]
You're welcome. Please feel free to open the issue if you need further help
