### ISSUE TITLE
Unable to configure lithnet MA

### ISSUE THREAD

**Issue by ADCS-MIMSYC** [lithnet/googleapps-managementagent#68]
![Lithnet](https://user-images.githubusercontent.com/87870826/126811726-241c59a1-8a1f-4c21-a302-b9c1ee40d3b8.PNG)

Need to know information about configuring schema 1 option

we tried below reference article but no luck.

https://github.com/lithnet/googleapps-managementagent/wiki/Installing-and-configuring-the-management-agent

**Comment by ryannewington** [comment]
Apologies for the delay in getting back to you @ADCS-MIMSYC 

Do you still require assistance for this issue?

As a starting point, the event log should have more specific information about this issue.
