### ISSUE TITLE
Change PrimaryEmail

### ISSUE THREAD

**Issue by JakobQv** [lithnet/googleapps-managementagent#69]
Is it possible to change an existing users PrimaryEmail?

**Comment by ryannewington** [comment]
Hi @JakobQv 

Yep! You have to issue a DN rename operation on the CS object itself. This will rename the primary email attribute.

**Comment by JakobQv** [comment]
Hello @ryannewington 
Thanks for the fast response, worked like a charm!

Regards,
Jakob
