### ISSUE TITLE
Need to modify the "archived" attribute

### ISSUE THREAD

**Issue by joselgarza** [lithnet/googleapps-managementagent#74]
We have added the scope "https://www.googleapis.com/auth/apps.licensing" to our API security, but we cannot seem to see the newly added "archived" attribute.  The issue is that we were simply evaluating Active and Suspended based on the Boolean attribute "suspended", but now we have to integrate our logic for archived users.  Our GoogleMA ended up changing users from archived to suspended previously, and we are trying to do this intentionally now via the GoogleMA.

So, the real question is, how can we "see" the archived attribute in Select Attributes in the MA?

**Comment by ryannewington** [comment]
@joselgarza Are you talking about the `archived` attribute on the user object, or something else to do with licensing? I'm not sure what the reference to that scope is.

Any attributes that are not exposed currently need to be added in code. If you can describe specifically what you need to do, I can look to see if I can add that capability for you

**Comment by joselgarza** [comment]
Yes, we need to see the "archived" Boolean attribute to set this during export.  This would allow us to have the three needed scenarios of Active, Suspended, and Archived.  To my knowledge, we just need to the ability to set the Boolean.

**Comment by joselgarza** [comment]
Additionally, we are validating with our Google contact to give an example of archiving a user via the REST API, just to ensure we are not missing any other attributes.  I would hate for you to do anything to the management agent, and the end result be lacking.  I will update when I can confirm.

**Comment by ryannewington** [comment]
@joselgarza 

I've added the archived attribute to the user object for you to test. Please let me know how it goes.

[Lithnet.GoogleApps.MA.Setup.msi.zip](https://github.com/lithnet/googleapps-managementagent/files/8101334/Lithnet.GoogleApps.MA.Setup.msi.zip)

**Comment by joselgarza** [comment]
I'm sorry for such a large delay.  My customer has postponed this issue, but I know we will return to it again as it is still outstanding.  Feel free to archive for now, and I will reach out when possible.

Jose Garza
Sr. Customer Engineer - Identity and Security
Office: 832.252.4300
Mobile: 281.795.7688
***@***.******@***.***>
***@***.***  [MIM_Logo]    [Server-2012-logo]    [azurecert]   ***@***.***

If you have any feedback about my work, please let either myself or my manager John Kowalik know at ***@***.******@***.***> or +1 540-449-3625.
